In [1]:
  for i in [1,2]:
      print(i)
      for j in ['A','B']:
          print(j)

1
A
B
2
A
B


In [5]:
def absolute_value(num):
  """# This function returns the absolute
  value of the entered number.
  It takes one numeric argument"""

  if num >= 0:
     return num
  else:
     return -num

print(absolute_value(-3))
print(absolute_value(23))

3
23


In [6]:
my_variable = 3
print(my_variable)

3


In [7]:
First_Name, Age, Gender = 'Ryan', '24', 'M'

print("First Name: ", First_Name)
print("Age: ", Age)
print("Gender: ", Gender)

First Name:  Ryan
Age:  24
Gender:  M


In [8]:
my_first_string = 'Mary had a'
my_second_string = "little lamb"

print(my_first_string)
print(my_second_string)

Mary had a
little lamb


In [9]:
multi_line_string = """Here is the first line.
Here is the second line.
Here is the third line."""

print(multi_line_string)

Here is the first line.
Here is the second line.
Here is the third line.


In [10]:
# Define and print lists with various variable types

list_of_integers = [1,2,3]
print(list_of_integers)

heterogeneous_list = [1, "CENGN", 2]
print(heterogeneous_list)

list_of_lists = [list_of_integers, [2,1], heterogeneous_list]
print(list_of_lists)

[1, 2, 3]
[1, 'CENGN', 2]
[[1, 2, 3], [2, 1], [1, 'CENGN', 2]]


In [11]:
x = [10, 20, 30, 40, 50, 60]

print(x)

[10, 20, 30, 40, 50, 60]


In [15]:
S = {-2, -1, 2, 3, 4}
def num_pos_neg(S):
    num_pos = 0
    num_neg = 0
    for i in S:
        if ( i >= 0 ):
            num_pos+=1
        else:
            num_neg+=1
    return num_pos, num_neg

pos, neg = num_pos_neg(S)
print("Number of positive numbers = ", pos)
print("Number of negative numbers = ", neg)

Number of positive numbers =  3
Number of negative numbers =  2


In [17]:
def multiply(lst):
    prod = 1
    for i in lst:
        prod = prod * i
    return prod

mylist = [1, 2, 3, 4, 5, 6, 7]
print(multiply(mylist))
mylist.append(multiply(mylist))
print(mylist)

5040
[1, 2, 3, 4, 5, 6, 7, 5040]


In [20]:
def factorial(x=3):
    def inner_factorial(y):
        prod = 1
        i = 1
        while (i <= y):
            prod *= i
            i += 1
        return prod
    
    if x > 0:
        return inner_factorial(x)
    else:
        print("Invalid input! Please enter a natural number to get factorial")
        return -1

print(factorial(5))
print(factorial())
print(factorial(-4))
        

120
6
Invalid input! Please enter a natural number to get factorial
-1


In [27]:
# Complete the code

import numpy as np
x = np.diag((1,1,1))
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [33]:
# Complete the code

import pandas as pd
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
print("\nAfter removing first three rows of the said DataFrame:")
df1 = df.drop([0,1,2])
print(df1)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

After removing first three rows of the said DataFrame:
   col1  col2  col3
3     4     9    12
4     7     5     1
5    11     0    11
